node {

		/* Cloning the Git repository to our Jenkins Workspace */
        stage('Checkout') {
            git url: 'https://github.com/antoniopaolacci/jenkins-sample-spring-microservices.git', credentialsId: 'github-credential', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install -DskipTests'
        }

        stage('Build Image') {
        
        	/* Change dir, cause after git checkout we are on /workspace/<dir-checkout>/ */
        	dir('jenkins-sample-discovery-service') {
        	
				/* This builds the actual image */
	            app = docker.build "jenkins-sample-discovery-service:1.0"
        	}
        	
        }

        stage ('Run Container') {
            /* This run the container from the image */
            docker.image("jenkins-sample-discovery-service:1.0").run('-p 8761:8761 -h discovery --name discovery')
        }
        
        /* Start another upstream pipeline */
        stage ('Final') {
            build job: 'jenkins-sample-account-service', wait: false
        }      

}