pipeline {   
    agent any    
    triggers {
        pollSCM '* * * * *'
    }    
    stages { 
        stage('Build') {
            steps {
                sh 'mvn clean install -DskipTests'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }
}