server:  
  port: ${PORT:3333}

eureka:  
  client:
    serviceUrl:    #If is set environment variable  DISCOVERY_URL use its value, otherwise use http://localhost:8761
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: true
   