node {

	/* Cloning the Git repository to our Jenkins Workspace */
    stage('Checkout') {
        git url: 'https://github.com/antoniopaolacci/jenkins-sample-spring-microservices.git', credentialsId: 'github-credential', branch: 'master'
    }

	/* Build all from parent pom */
    stage('Build') {
        sh 'mvn clean install -DskipTests'
    }

    stage('Build Docker Image') {
    
    	/* Change dir, cause after git checkout we are on /workspace/<dir-checkout>/ */
    	dir('jenkins-sample-gateway-service') {
    	
			/* This builds the actual image */
			app = docker.build "antoniopaolacci/jenkins-sample-gateway-service:1.0"
    	} 
    }

    stage ('Run Docker Container') {
       
       try {
	        /* This run the container from the image */
	        docker.image("antoniopaolacci/jenkins-sample-gateway-service:1.0").run('-h gateway --name gateway --link discovery') 
       } catch (err) {
	  	   echo "Container already created."
	   } 
 
    }
    
}