node {

  /* Groovy script to build my application */
  def app

 		stage('Checkout') {   
 			 /* Cloning the Repository to our Workspace */
             echo 'Checkout from file system...'
             checkout filesystem(clearWorkspace: false, copyHidden: false, path: 'D:\\MyJavaProgetti\\my-microservice-architecture\\jenkins-sample-spring-microservices\\jenkins-sample-customer-service')	
        }
        
        stage('Build') {
            sh 'mvn clean install -DskipTests'
        }

        stage('Build Docker Image') {
            /* This builds the actual image */
            app = docker.build "antoniopaolacci/jenkins-sample-customer-service:1.0"
        }

        stage ('Run Docker Container') {
            /* This run the container from the image */
            docker.image("jenkins-sample-customer-service:1.0").run('-p 3333:3333 -h customer --name customer')
        }

	    stage('Push image') {
	        /* You would need to first register with DockerHub before you can push images to your account*/			
			echo "Trying to Push Docker Build to DockerHub"
	        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
	            app.push("latest")
	        }  
	    }   
	    
}
