node {

  /* Groovy script to build my application */
  def app

 		stage('Checkout') {   
 			 
 			 /* Cloning the project to our Jenkins Workspace */
             echo 'Checkout from file system...'
             checkout filesystem(clearWorkspace: false, copyHidden: false, path: 'D:\\MyJavaProgetti\\my-microservice-architecture\\jenkins-sample-spring-microservices\\jenkins-sample-customer-service')	
        }
        
        stage('Build') {
            sh 'mvn clean install -DskipTests'
        }

        stage('Build Docker Image') {
            /* This builds the actual image */
            app = docker.build "antoniopaolacci/jenkins-sample-customer-service:1.0"
        }
        
		// This run the container from the image
        stage ('Run Docker Container') {
            docker.image("jenkins-sample-customer-service:1.0").run('-p 3333:3333 -h customer --name customer')
        }

	    stage('Push image') {
	            	
			echo "Trying to Push Docker Build to DockerHub..."
	        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
	            app.push("latest")
	        }   
	    }
	    
	    stage ('Wait for approval') {
           input 'Approve deployment on K8s?'
        }
	    
	    // Deploy Application on K8s
	    // before configure $HOME/.kube/config secret file
	    stage('Deploy Application on K8s') {
	       
	       echo 'Deploying on K8s'
           
	       /* change dir */
        	dir('kubernetes') {
	            kubeconfig(credentialsId: 'mykubeconfig', serverUrl: 'https://kubernetes.docker.internal:6443') {
	                sh 'kubectl config view'
	                sh 'kubectl api-resources'
	                sh 'kubectl apply -f deployment.yml'
	            }     
	        }
	   }   
	    
}
